options:
  platform:     psx
  basename:     boot
  base_path:    .
  target_path:  ../SLUS_010/SLUS_010.71
  asm_path:     ../asm/boot
  asset_path:   ../assets/boot
  src_path:     ../src/boot
  # compiler
  compiler: GCC
  # disasm/linker
  symbol_addrs_path:    symbol_addrs.boot.txt
  undefined_syms_path:  undefined_syms.boot.txt
  undefined_funcs_auto_path:  undefined_funcs_auto.boot.txt
  undefined_syms_auto_path:   undefined_syms_auto.boot.txt
  find_file_boundaries: yes
  enable_ld_alignment_hack: yes
  use_legacy_include_asm: no
  gp_value: 0x8009a6d0
  section_order:
  - .rodata
  - .text
  - .data
  - .bss
segments:
  - [0x0, header]    # data?
  - [0x84, bin]      # zero padding
  - name:  main
    type:  code
    start: 0x00000800
    vram:  0x80010000    # per header
    subalign: 4
    subsegments:
      - [0x800, bin]       # data
      - [0x333C,c]         # first function
      - [0x9590,asm]       # GsGetWorkBase
      - [0x95BC,c]         # Continue Game functions
      - [0x9808,c]         # Main Function
      - [0xAC94,asm]       # GsGetWorkBase_0
      - [0xACA4,c]         # Continue Game functions
      - [0x1320C, asm]     # InitCard
      - [0x13264, c]       # Continue Game functions
      - [0x1B260, asm]     # DsFlush
      - [0x1B290, c]       # Continue Game functions
      - [0x51D88, asm]     # Start Function
      - [0x51E44, asm]     # start of library funnctions
      - [0x59C64, c]       # 2 functions
      - [0x59CA4, asm]     # Another set of library functions
      - [0x69564, c]       # InitMemoryCard_80078D64
      - [0x69594, asm]     # Another set of library functions
      - [0x6FC1C, bin]     #data
  - [0x7C000]